version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'

    ports:
      - '5672:5672'
      - '15672:15672'

    networks:
      - network
  activemq:
    image: webcenter/activemq:5.14.3
    restart: "no"
    environment:
      TZ: "Asia/Ekaterinburg"
      TIME_ZONE: "Asia/Ekaterinburg"
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_ADMIN_PASSWORD: "admin"
      ACTIVEMQ_CONFIG_MINMEMORY: "512"
      ACTIVEMQ_CONFIG_MAXMEMORY: "512"
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"

networks:
  network: {}